export const Routes = {
  home: '/' as const,
  camera: '/camera' as const,
  barcodeCamera: '/barcodeCamera' as const,
  cameraTypeSelect: '/cameraSelection' as const,
  search: '/search' as const,
  productConfirm: '/product/confirm' as const,
  productCreate: '/product/create' as const,
  productDetails: (id: number) => `/product/details/${id}` as const,
  productDetails: (id: number) => `/product/details/${id}` as const,
  priceCollaborate: '/price/collaborate' as const,
  priceDetails: (id: number) => `/price/details/${id}` as const,
  priceHeatmap: (id: number) => `/price/heatmap/${id}` as const,
  profile: '/profile' as const,
  cart: '/cart' as const,
  cartCompare: '/cart/compare' as const,
  validation: '/validation' as const,
};