import { Colors, Radius, Spacing, Typography } from '@/constants/theme';
import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: Colors.background },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: Colors.border,
  },
  toolbar: {
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.md,
    gap: Spacing.sm,
    borderBottomWidth: 1,
    borderBottomColor: Colors.border,
    backgroundColor: Colors.surface,
  },
  searchWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colors.background,
    borderRadius: Radius.md,
    borderWidth: 1,
    borderColor: Colors.border,
    paddingHorizontal: Spacing.sm,
    gap: Spacing.xs,
  },
  searchInput: {
    flex: 1,
    padding: Spacing.sm,
    fontSize: Typography.sizes.md,
    color: Colors.text,
  },

  // Segmented filter control
  sortLabel: {
    color: Colors.textMuted,
    fontSize: Typography.sizes.xs,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    fontWeight: Typography.weights.semibold,
    marginBottom: 2,
  },
  sortRow: {
    flexDirection: 'row',
    backgroundColor: Colors.background,
    borderRadius: Radius.md,
    borderWidth: 1,
    borderColor: Colors.border,
    padding: 3,
    gap: 3,
  },
  sortButton: {
    flex: 1,
    paddingVertical: Spacing.xs,
    paddingHorizontal: Spacing.sm,
    borderRadius: Radius.sm,
    alignItems: 'center',
  },
  sortButtonActive: {
    backgroundColor: Colors.primary,
  },
  sortText: {
    color: Colors.textSecondary,
    fontSize: Typography.sizes.sm,
    fontWeight: Typography.weights.medium,
  },
  sortTextActive: {
    color: Colors.white,
    fontSize: Typography.sizes.sm,
    fontWeight: Typography.weights.semibold,
  },

  list: { padding: Spacing.md, gap: Spacing.md },

  // Scorecard
  scorecard: {
    alignItems: 'center',
    justifyContent: 'center',
    gap: 2,
    alignSelf: 'center',
    width: 120,
    height: 120,
    marginTop: Spacing.md,
    backgroundColor: Colors.surface,
    borderRadius: Radius.lg,
    borderWidth: 1,
    borderColor: Colors.border,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 6,
    elevation: 1,
  },
  scorecardIconWrap: {
    width: 36,
    height: 36,
    borderRadius: Radius.md,
    backgroundColor: Colors.primary + '14',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 4,
  },
  scorecardNumber: {
    fontSize: Typography.sizes.xxxl,
    fontWeight: Typography.weights.bold,
    paddingTop: 15,
    color: Colors.primaryDark,
  },
  scorecardLabel: {
    fontSize: Typography.sizes.sm,
    color: Colors.textSecondary,
  },

  // Product card
  itemCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colors.surface,
    borderRadius: Radius.lg,
    padding: Spacing.md,
    gap: Spacing.sm,
    borderWidth: 1,
    borderColor: Colors.border,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 2,
  },
  itemCardSelected: {
    borderWidth: 2,
    borderColor: Colors.primary,
    backgroundColor: Colors.primary + '0D',
  },
  itemIconWrap: {
    width: 44,
    height: 44,
    borderRadius: Radius.md,
    backgroundColor: Colors.primary + '14',
    alignItems: 'center',
    justifyContent: 'center',
  },
  checkbox: {
    width: 22,
    height: 22,
    borderRadius: 11,
    borderWidth: 2,
    borderColor: Colors.border,
    alignItems: 'center',
    justifyContent: 'center',
  },
  checkboxSelected: {
    backgroundColor: Colors.primary,
    borderColor: Colors.primary,
  },
  itemInfo: { flex: 1, gap: 3 },
  itemName: { fontWeight: Typography.weights.semibold },
  itemActions: { alignItems: 'flex-end', gap: Spacing.sm },
  itemPrice: {
    color: Colors.primary,
    fontWeight: Typography.weights.bold,
    fontSize: Typography.sizes.md,
  },
  actionButtons: { flexDirection: 'row', gap: Spacing.sm },
  actionButton: {
    width: 34,
    height: 34,
    borderRadius: Radius.sm,
    backgroundColor: Colors.primary + '14',
    alignItems: 'center',
    justifyContent: 'center',
  },
  deleteActionButton: {
    backgroundColor: Colors.error + '14',
  },

  empty: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: Spacing.md,
  },
  overlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.45)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: Spacing.lg,
  },
  popup: {
    backgroundColor: Colors.surface,
    borderRadius: Radius.lg,
    padding: Spacing.lg,
    width: '100%',
    gap: Spacing.sm,
  },
  popupTitle: { textAlign: 'center' },
  popupSubtitle: { textAlign: 'center' },
  deleteButton: {
    backgroundColor: Colors.error,
    borderRadius: Radius.sm,
    padding: Spacing.md,
    alignItems: 'center',
    marginTop: Spacing.sm,
  },
  cancelButton: { alignItems: 'center', padding: Spacing.sm },
  priceInput: {
    borderWidth: 1,
    borderColor: Colors.border,
    borderRadius: Radius.sm,
    padding: Spacing.md,
    fontSize: Typography.sizes.md,
    color: Colors.text,
    backgroundColor: Colors.background,
  },

  // Stale-price review section
  staleSection: {
    marginHorizontal: Spacing.sm,
    marginTop: Spacing.md,
    padding: Spacing.sm,
    borderRadius: Radius.lg,
    backgroundColor: Colors.primary + '0D',
    borderWidth: 1,
    borderColor: Colors.primary + '33',
  },
  staleSectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.xs,
    marginBottom: Spacing.sm,
  },
  staleSectionTitle: {
    flex: 1,
    color: Colors.text,
  },
  staleList: { gap: Spacing.sm },
  staleListContainer: {
    maxHeight: 160,
  },
  staleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colors.surface,
    borderRadius: Radius.md,
    padding: Spacing.sm,
    gap: Spacing.sm,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  staleRowKept: {
    backgroundColor: Colors.success + '14',
    borderColor: Colors.success,
  },
  staleRowInfo: { flex: 1, minWidth: 0, gap: 2 },
  staleRowName: { fontWeight: Typography.weights.semibold },
  staleRowUpdated: { fontStyle: 'italic' },
  staleRowActions: { gap: Spacing.md },
  staleUpdateButton: {
    paddingHorizontal: Spacing.sm,
    paddingVertical: Spacing.xs,
    borderRadius: Radius.sm,
    backgroundColor: Colors.primary,
  },
  staleUpdateButtonText: {
    color: Colors.white,
    fontWeight: Typography.weights.semibold,
    fontSize: Typography.sizes.md,
  },
  staleKeepButton: {
    paddingHorizontal: Spacing.sm,
    paddingVertical: Spacing.xs,
    borderRadius: Radius.sm,
    borderWidth: 1,
    borderColor: Colors.success,
  },
  staleKeepButtonText: {
    color: Colors.success,
    fontWeight: Typography.weights.semibold,
    fontSize: Typography.sizes.md,
  },
  staleKeptBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  staleKeptText: {
    color: Colors.success,
    fontWeight: Typography.weights.semibold,
  },
});