import { Colors, Radius, Spacing, Typography } from '@/constants/theme';
import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: Colors.white },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: Spacing.lg,
    borderBottomWidth: 1,
    borderBottomColor: Colors.border,
  },
  scroll: { flex: 1 },
  form: { padding: Spacing.lg, gap: Spacing.md, paddingBottom: Spacing.xxl },
  label: {
    fontSize: Typography.sizes.sm,
    fontWeight: Typography.weights.medium,
    color: Colors.text,
    marginBottom: Spacing.xs,
  },
  input: {
    borderWidth: 1,
    borderColor: Colors.border,
    borderRadius: Radius.md,
    paddingHorizontal: Spacing.md,
    paddingVertical: 12,
    fontSize: Typography.sizes.md,
    color: Colors.text,
  },
  inputError: { borderColor: Colors.error },
  errorText: { fontSize: Typography.sizes.xs, color: Colors.error, marginTop: 4 },
  searchSection: { zIndex: 10 },
  searchRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
    borderWidth: 1,
    borderColor: Colors.border,
    borderRadius: Radius.md,
    paddingHorizontal: Spacing.md,
    paddingVertical: 12,
  },
  searchInput: { flex: 1, fontSize: Typography.sizes.md, color: Colors.text, padding: 0 },
  dropdown: {
    borderWidth: 1,
    borderColor: Colors.border,
    borderRadius: Radius.md,
    marginTop: 4,
    backgroundColor: Colors.white,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 4,
    overflow: 'hidden',
  },
  predictionItem: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: Spacing.sm,
    paddingHorizontal: Spacing.md,
    paddingVertical: 12,
  },
  predictionText: { flex: 1 },
  predictionMain: { fontSize: Typography.sizes.md, color: Colors.text, fontWeight: Typography.weights.medium },
  predictionSub: { fontSize: Typography.sizes.sm, color: Colors.textSecondary, marginTop: 2 },
  separator: { height: 1, backgroundColor: Colors.border, marginHorizontal: Spacing.md },
  mapCard: {
    borderRadius: Radius.lg,
    borderWidth: 1,
    borderColor: Colors.border,
    overflow: 'hidden',
  },
  mapHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    padding: Spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: Colors.border,
  },
  mapHeaderText: { fontSize: Typography.sizes.sm, fontWeight: Typography.weights.semibold, color: Colors.primary },
  mapImage: { width: '100%', height: 160 },
  mapAddress: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 6,
    padding: Spacing.md,
    paddingBottom: Spacing.sm,
  },
  mapAddressText: { flex: 1, fontSize: Typography.sizes.md, color: Colors.text },
  correctButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    borderTopWidth: 1,
    borderTopColor: Colors.border,
    padding: Spacing.md,
  },
  correctButtonText: { fontSize: Typography.sizes.sm, color: Colors.primary, fontWeight: Typography.weights.medium },
  chips: { flexDirection: 'row', flexWrap: 'wrap', gap: Spacing.sm },
});